### PR TITLE
Add `mode` option to support passing vega specs

### PR DESCRIPTION
**Pull request by mathisonian**
So you can do this:

```
[IdyllVegaLite mode:"vega" spec:`{ ... }`  /]
```

Note - I'm not sure this will work with `width: "container"` you may have to pass an explicit width. I also added a note about how to set up aliases in the readme, so you can write something like 

```
[Plot mode:"vega" spec:`{ ... }`  /]
```

for readability.

### CODE REVIEW

**Comment by danmarshall** [comment]
I tried running this branch, and got some errors when invoking the Idyll server:

package.json:
```json
 ...
  "dependencies": {
    ...
    "idyll-vega-lite": "git+https://github.com/idyll-lang/idyll-vega-lite.git#vega-support",
  },
...
```
Node.js error:
```
Error occurred in Idyll expression
ReferenceError: __idyllReturnValue is not defined
```
The document appears in the browser, but without a rendered vega-lite chart. And more errors in the browser.

**Comment by danmarshall** [comment]
Oh nvm, the error my bad I was passing bad json. Also I see that this file needs to be built into lib.js to be used.

But, I don't think this will work just yet because the `data` property of vega-lite has a different schema than vega. Vega expects its data items to have a `name` property.

**Comment by mathisonian** [comment]
Thanks for the PR @danmarshall! 

I'm going to test this locally a bit more, then will merge and cut a release.

**Comment by mathisonian** [comment]
Okay everything looks good to me. 

I added a little additional logic to infer the mode based on the spec's `$schema` property in the case that mode isn't passed explicitly, plus updated the README with more usage info.

**Pull request merged**
